### PR TITLE
Bug/issues 59

### PR DESCRIPTION
**Pull request by psygate**
Fix the update problem where the primary key cant be dropped if a table contains foreign keys.

### CODE REVIEW

**Comment by Maxopoly** [comment]
Needs to be separated from the OctTree stuff or it'll hang together with that PR

**Comment by psygate** [comment]
Seperated.

**Comment by Protonull** [comment]
Small critique, but you're pushing changes that actively violate the style guide that weren't otherwise, like separated and wildcard imports.

**Comment by psygate** [comment]
Updated class & editorconfig to reflect the demand for single class imports.

**Comment by wingzero54** [comment]
Fixed by [this commit](https://github.com/CivClassic/CivModCore/commit/cc7122723cd18a92b5384ee32adbb0a90ba33d2b), it was an issue with changes to MariaDB and updating the statement allows it to work as-is.

**Pull request closed without merging**
