### PR TITLE
Laying waste to CMC 🤪

### PR DESCRIPTION
**Pull request by Protonull**

### CODE REVIEW

**Comment by Maxopoly** [comment]
Oof

**Comment by Protonull** [comment]
Oh also the increased version means that anything still on 1.8.0 wont suddenly have a bunch of deprecation warnings and everything will still work since this is all backwards compatible.

**Comment by Protonull** [comment]
It might be work genuinely considering making Paper a hard dependency. While helping out someone on the PaperMC Discord, I was directed towards [MaterialTags](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/MaterialTags.html), which looking at it would remove the need to have and maintain [MoreTags](https://github.com/CivClassic/CivModCore/blob/54e09f072540e5a6d446d6706121570ef9ca3ce2/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/MoreTags.java) which itself is an update to [MaterialAPI](https://github.com/CivClassic/CivModCore/blob/4b4f2df810b8467627a97444427ee4b80de2b148/src/main/java/vg/civcraft/mc/civmodcore/api/MaterialAPI.java). Paper is just becoming too useful to ignore and I think we ought to succumb.

**Comment by Protonull** [comment]
Going to be retiring this PR soon, it's clear it's too big an ask.

**Comment by Protonull** [comment]
Closing this PR since I accidentally orphaned it and I can't find a way to fix it. Plus I doubt this would've been merged anytime soon anyway.

**Pull request closed without merging**
